name: Daily Commit

on:
  schedule:
    - cron: "15 10 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update log
        run: |
          mkdir -p logs
          date >> logs/auto.md

      - name: Commit and push
        run: |
          git config user.name "jack25sh"
          git config user.email "jack25sh@outlook.com"
          git add .
          git commit -m "daily activity" || echo "No changes"
          git push
