name: Daily Commit

on:
  schedule:
    - cron: "15 10 * * *" # щодня
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update log
        run: |
          echo "- Auto update $(date)" >> logs/auto.md

      - name: Commit changes
        run: |
          git config user.name "jack25sh"
          git config user.email "jack25sh@outlook.com"
          git add .
          git commit -m "daily update"
          git push
